rabbit1:
  image: grandmore/rabbitmq-cluster
  hostname: rabbit1
  mem_limit: 128m
  environment:
    - ERLANG_COOKIE=abcdefg
  volumes:
    - ./rabbit1:/var/lib/rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
    - "15670:15670"
    - "15674:15674"
rabbit2:
  image: grandmore/rabbitmq-cluster
  hostname: rabbit2
  mem_limit: 128m
  links:
    - rabbit1
  volumes:
    - ./rabbit2:/var/lib/rabbitmq
  environment:
    - ERLANG_COOKIE=abcdefg
    - CLUSTER_WITH=rabbit1
#  ports:
#    - "5673:5672"
#    - "15673:15672"
rabbit3:
  image: grandmore/rabbitmq-cluster
  hostname: rabbit3
  mem_limit: 128m
  links:
    - rabbit1
    - rabbit2
  volumes:
    - ./rabbit3:/var/lib/rabbitmq
  environment:
    - ERLANG_COOKIE=abcdefg
    - CLUSTER_WITH=rabbit1
#  ports:
#    - "5674:5672"
#    - "15674:15672"
